### ISSUE TITLE
New Pipeline discussion

### ISSUE THREAD

**Issue by eigoshimizu** [eigoshimizu/Genomon#1]
ここで、コメントなどの議論ができます。

**Comment by eigoshimizu** [comment]
Items to support

1) @active_if 
2) config file backup. Change the name not to conflict with previous job submission.
3) Job resubmition with memory x 2.

**Comment by ken0-1n** [comment]
genomonをinstallから実行までの手間を省くための案を出す場所

① hgcスパコンでgenomonを使うのであれば、HGCにbwaやsamtoolsがインストールされており、そのpathがgenomon.cfgに記載されていると便利です。
②hgc以外のスパコンで使うのであれば、samtoolsはgenomonに組み込んだ方が便利だと思います。mapsplice2ではsamtoolsが組み込まれており、samtoolsのインストールという手順がなくなって、使う側としてはうれしいです。（mapspliece2がどのような方法をとっているかは未確認）

**Comment by ken0-1n** [comment]
pip install --user yaml ができなかった。
環境： ngw03
pip path： /usr/local/package/python2.7/2.7.2/bin/pip
コンソールに出力されたログ:
Downloading/unpacking yaml
  Real name of requirement yaml is yaml
  Could not find any downloads that satisfy the requirement yaml
No distributions at all found for yaml
Storing complete log in /home/kchiba/.pip/pip.log

pip install --user pyyamlはできた。

**Comment by ken0-1n** [comment]
genomon.yaml　のtestディレクトリで実行できるサンプルが欲しいです。

**Comment by eigoshimizu** [comment]
python yamlのインストールは、
　　　pip install --user pyyaml
です。
READMEを変更します。

**Comment by eigoshimizu** [comment]
テストのための環境をもう少しキチン整えます。
genomon.job(yaml) を変更します。

**Comment by eigoshimizu** [comment]
変更点、

yamlのインストール
    pip install --user pyyaml

ディレクトリ構造とgenomon.job の整合性
README.md

├── scripts --> copy *.py scripts here.
└── test  --> this is the path for project_root in genomon.job
    └── project_name  --> this is proect in genomon.job.
        └── data
            └── 20150303 --> this is sample_date in genomon.job
                └── test01 --> this is sample_name in genomon.job.

genomon.job
    project
    sample_name
    sample_date

genomon.cfg は、変更なしでそのままテストできます。
千葉さんのご指摘のように、HGCで提供されているモジュールは、提供されているものを使用します。

その他のツールに関しては、 MapSplice2を調べたところ、ソースコードがパッケージの中に含まれており、全てビルドするようです。
インストールのパッケージの作成に関しても、考えてみます。

**Comment by ken0-1n** [comment]
対応ありがとうございます。
TASK_IDの単位など問題なく使いやすいです。

**Comment by ken0-1n** [comment]
入力FASTQファイルディレクトリと出力ファイルディレクトリはユーザ側で指定できることが希望です。
現行のGenomonが入力ディレクトリ固定でしたが、作るのが面倒だと不評です。

ミーティングで話した、ディレクトリ構成は、プログラムで固定するのではなく、運用ルールくらいの縛りの方がフレキシブルで喜ばれます。

**Comment by eigoshimizu** [comment]
ディレクトリ構成について、
1) genomon.job( yaml )に, input_file_dir を追加します。こんな感じ。
input_file_dir:             /home/eigos/Data/GenomonProj/genomon_test/data/20150216/test01
input_file_type:            paired #paired, single, illumina
fastq_file:                 ?_100_{pair_id}.fastq
pair_id:
                            - 1
                            - 2

2) 実際のディレクトリ構造は、genomon.job(yaml)の中に定義するようにします。

こんな感じで実装の作業を進めます。

**Comment by eigoshimizu** [comment]
input_file_dir から、 project_root->project->data->sample_date->sample_name に symbolic link を貼ります。

**Comment by ken0-1n** [comment]
1つのプロジェクトで、TCGAのデータを解析するときには、exomeで300件とかあります。
サンプル毎にgenomon.job を書き換えなければならないとなると面倒だと感じます。

大量のサンプルの解析が手間なくできるのであれば、問題ないです。

**Comment by eigoshimizu** [comment]
yaml job configuration file の仕様をアップデートしました。
input_file_dir の下に複数のサブディレクトリを作って、その中にデータを置いておくと、まとめて解析してくれます。
詳しくは、 test/genomon.job をご覧ください。

**Comment by friend1ws** [comment]
要望
１．inputにfastqのpathのリストを指定出来ればうれしいです。
２．必ずしも必要でないパッケージは、その機能を使わないならばインストールしなくても問題ないということであればうれしいです（例えばいまcut adaptはほとんどやらないので）pip install --user cutadapt

**Comment by eigoshimizu** [comment]
使用しないツールはインストールしていなくても問題はありません。
annovar以外のツールは、/home/w3varann にインストールしました。
genomon.cfg内に指定してあるツールで、自分でインストールする必要があるものは、annovarのみとなります。

**Comment by eigoshimizu** [comment]
Input に fastq の path のリストを指定できるようにすることに関しては、すこり考察が必要です。

**Comment by eigoshimizu** [comment]
Input に fastq の path のリストを指定できるようにする件は、別スレッドを立ち上げました。
このスレッドは、クローズします。
