### ISSUE TITLE
illuminaで生成されたFASTQのvendor quality checksについて

### ISSUE THREAD

**Issue by ken0-1n** [eigoshimizu/Genomon#14]
Casava 1.8+であれば、デフォルトでフィルタされる。
genomonでは、フィルタ処理のON/OFFを切り替えられるようにする。デフォルトはOFF（CASAVAでやっていることを想定）とする。

**Comment by eigoshimizu** [comment]
対応いたしました。

fastq_filter:               False # True or False

デフォルトは、False です。
