### ISSUE TITLE
README.mdが文字化けしました。

### ISSUE THREAD

**Issue by ken0-1n** [eigoshimizu/Genomon#18]
29 ▒~T~\▒~T~@▒~T~@ scripts --> copy *.py scripts here.
 30 ▒~T~T▒~T~@▒~T~@ test  --> this is the path for project_root in genomon.job
 31     ▒~T~T▒~T~@▒~T~@ project_name  --> this is project in genomon.job.
 32         ▒~T~T▒~T~@▒~T~@ data
 33             ▒~T~T▒~T~@▒~T~@ 20150303 --> this is sample_date in genomon.job
 34                 ▒~T~T▒~T~@▒~T~@ test01 --> this is sample_name in genomon.job.

**Comment by eigoshimizu** [comment]
とりあえず、ダブルバイトの文字は使用しないようにします。
よろしくお願いいたします。
