### ISSUE TITLE
exit statusについて

### ISSUE THREAD

**Issue by ken0-1n** [eigoshimizu/Genomon#20]
biobambamのbamsortでエラー終了したときに、qreportで表示されるexit statusが1になっていた。
呼び出したツールのexit statusをqreportで見られるようにしてほしい。

**Comment by eigoshimizu** [comment]
bwa_mem で bamsort する場合に、   
calmdnmreference=/home/mimorin/genomon/ref/GRCh37-lite_PCAWG_bwa-0.7.10/GRCh37-lite_PCAWG.fa.gz

を指定すると失敗する。
Job の exit status は、1 でした。
qreport でも、 exit_stauts = 1 でした。


 command = -t 1-5:1, /home/eigos/Data/GenomonProj/genomon/results/20150423/20150409_small/script/bwa_mem_20150423_1638_285464.sh
    memory  = 6G
    job     = sjob

    STDOUT: Your job-array 9139634.1-5:1 ("bwa_mem_20150423_1638_285464.sh") has been submitted
Job 9139634.2 exited with exit code 1.
Job 9139634.1 exited with exit code 1.
Job 9139634.5 exited with exit code 1.
Job 9139634.3 exited with exit code 1.
Job 9139634.4 exited with exit code 1.

==============================================================
owner                eigos                                                       
jobnumber            9139634                                                     
taskid               1                                                           
slots                1                                                           
pe_taskid            NONE                                                        
granted_pe           NONE                                                        
exit_status          1                                                           
failed               0                                                           
qname                sjobs.q                                                     
hostname             nc488i                                                      
jobname              bwa_mem_20150423_1638_285464.sh                             
qsub_time            20150423-16:38:57                                           
start_time           20150423-16:39:15                                           
end_time             20150423-16:39:35                                           
ru_wallclock         20                                                          
cpu                  15.3                                                        
mem                  53.0                                                        
maxvmem              5.2G                                                        
r_mem                6G                                                          
r_q                  sjob                                                        
r_cpu                NONE                                                        
qdel                 NONE                                                        
failed_txt           N/A                                                         
recommended_queue    sjobs.q                                                     
recommended_memory   6G                                                          
recommended_option   -l s_vmem=6G,mem_req=6,sjob

**Comment by ken0-1n** [comment]
bwaをqdelしたのですが、markduplicatesが走ってしまいました。
また、別の問題でしょうか？

**Comment by eigoshimizu** [comment]
qdel でジョブを kill すると、 exit status は、 0 で帰ってくるので、pipeline の中では catch することができませんでした。
STDOUT にメッセージが、

    STDOUT: Your job 109914 ("markduplicates_20150424_1012_900220.sh") has been submitted
Unable to run job 109914

とでるので、 'Unable to run job' の部分を catch して、 pipeline を停止するようにしました。
ご協力ありがとうございます。
