### ISSUE TITLE
再実行時のファイルチェックについて

### ISSUE THREAD

**Issue by ken0-1n** [eigoshimizu/Genomon#23]
unsorted.bamが未完成なBAMであっても、genomonパイプラインを再実行すると、bwa memが完了していると判定される。

**Comment by eigoshimizu** [comment]
それぞれの処理の結果を、フラグファイルとしてセーブします。
再実行するときは、そのフラグを見て、失敗していれば、再実行します。

フラグファイルは、configのディレクトリに配置します。
下記の例だと、20150603_1559_948433　に実行した時に、split_fastq が実行され、結果の exit status が、0になります。
ファイル名のフォーマットは、
genomon_{year}{month}{date}_{time}_{microsecond}_{process}_{output_file}_r{exit_code}

フラグファイルの例）
genomon_20150603_1559_948433_param.yaml
genomon_20150603_1559_948433_job.yaml
genomon_20150603_1559_948433.cfg
genomon_20150603_1559_948433_split_fastq_g_g_100_1_r0
genomon_20150603_1559_948433_split_fastq_h_h_100_1_r0

genomon_20150603_1610_214891_param.yaml
genomon_20150603_1610_214891_job.yaml
genomon_20150603_1610_214891.cfg
genomon_20150603_1610_214891_bwa_mem_g_g_100_1_r0
genomon_20150603_1610_214891_bwa_mem_h_h_100_1_r0
genomon_20150603_1610_214891_markduplicates_small_markdup_r0

現在テスト中です。

**Comment by eigoshimizu** [comment]
実装しました。
ありがとうございます。
