### ISSUE TITLE
biobambamのソートでfasta indexがなくてエラーになった。

### ISSUE THREAD

**Issue by ken0-1n** [eigoshimizu/Genomon#24]
アライメントが実行前に、事前に存在チェックするなどの対応が必要かと思われます。
現状ではアライメントが完了⇒ソート時にfasta indexがなくてエラーとなる。

別件になってしまうかもしれませんが、
アライメントが完了してソートで落ちたときに、再度アライメントから開始するのは、もったいないと思いますので、アライメントとソートを別のタスクにできればした方が良いかと思います。

**Comment by eigoshimizu** [comment]
実行する前に、 job yaml ファイルと、 system config ファイルの内容を確認する作業が必要になります。

**Comment by eigoshimizu** [comment]
fasta index がない場合は、作るように変更しました。
作成に失敗した場合は、exit します。
