### ISSUE TITLE
FASTQファイルをワイルドカードで指定した時のジョブ(split_fastq)の入り方について

### ISSUE THREAD

**Issue by ken0-1n** [eigoshimizu/Genomon#26]
同一サンプルのFASTQが2つ以上あるときには、FASTQのファイルの数だけ、同時にsplit fastq処理に投入される方がよいのではないかと考えます。

**Comment by eigoshimizu** [comment]
python genomon.py  --jobs 8 
で、指定される数だけ並列処理されるまず。

--jobs に１より大きい数を指定して、実行してみてください。
よろしくお願いいたします。

**Comment by eigoshimizu** [comment]
動いていると思いますので、この件は、クローズします。
問題がある場合は、さいどopenしてください。
よろしくお願いいたします。
