### ISSUE TITLE
１つのジョブで生成されるmark duplicate済みのbamファイルは１つにしてほしい。

### ISSUE THREAD

**Issue by ken0-1n** [eigoshimizu/Genomon#29]
同じサンプルで、入力のFASTQファイルが複数あっても、
1ジョブで生成されるmark duplicate済みのbamファイルは、１つにマージされていると使いやすいです。

現状では、FASTQファイルごとにmark duplicate済みのbamが生成されます。

**Comment by eigoshimizu** [comment]
サポートしました。
