### ISSUE TITLE
[yaml]　指定するパラメータをtasks typeでわけた方が良い。

### ISSUE THREAD

**Issue by ken0-1n** [eigoshimizu/Genomon#30]
異なるtaskで同じパラメータを指定する場合があるので、task type毎に、指定するパラメータを分けておいた方が良いと思います。
例）
# Fisher's exact test mutation call
base_quality:           15
map_quality:            30

# ebcall 
base_quality:           15
map_quality:            30

**Comment by eigoshimizu** [comment]
こんな感じでせっていするようにしました。　よろしくお願いいたします。

parameters:
# parameters for split fastq
    split_fastq:
        split_fastq_line_number:    20
        fastq_filter:               False # True or False
# bwa mem
    bwa_mem:
        bwa_read_group:     '@RG\tID:Small\tSM:test_sample\tLB:Test\tPL:Illumina\tPU:flowcell-barcode\tCN:HGC\tPI:500'
        min_score:          20 # used for -T option of bwa mem

# cutadapt
    cutadapt:
        adaptor:
                        - NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
                        - NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

# Fisher's exact test mutation call
    fisher_mutation_call:
        min_depth:              9
        max_indel:              2
        max_distance:           5
        base_quality:           15
        map_quality:            30

**Comment by eigoshimizu** [comment]
Git hub に反映しました。
