### ISSUE TITLE
[yaml] 入力ファイルとツールの設定値は別ファイルにしてほしい

### ISSUE THREAD

**Issue by ken0-1n** [eigoshimizu/Genomon#31]
通常、1つのがん種を研究するときには複数のサンプル（がん細胞をシークエンスしたデータ）を使用します。
そのとき、サンプル毎に、マッピングクオリティーなどのツールの設定値を変更することはなく、プロジェクトで扱っている複数のサンプル単位で、設定値を変更します。
そのため、ツールの設定値が書いてあるyamlはプロジェクトで１つだけの方が扱いやすいです。たとえば、quality thresholdを全てのサンプルで0.5⇒0.2に変更して再実行しようとしたときに、１つの設定値だけ変更すれば良いのであれば便利です。

**Comment by eigoshimizu** [comment]
対応いたします。
よろしくお願いいたします。

**Comment by eigoshimizu** [comment]
対応完了いたしました。
サンプルは,　samples ディレクトリをご覧ください。
