### ISSUE TITLE
execute star with run.sh =>  python error

### ISSUE THREAD

**Issue by roko-t** [eigoshimizu/Genomon#38]
File "/usr/local/package/python2.7/current/lib/python2.7/multiprocessing/process.py", line 309, in __init__
    self._authkey = AuthenticationString(os.urandom(32))
AttributeError: 'module' object has no attribute 'urandom'

＝＝＝＞
　export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/package/python2.7/current/lib
　だったので　
　PYTHONHOME=/usr/local/package/python2.7/current　にしてみたが、解決せず
　/usr/local/package/python2.7/2.7.2/bin/python　を使用していたので
   PYTHONHOME=/usr/local/package/python2.7/2.7.2 を指定してエラー解決

**Comment by eigoshimizu** [comment]
/home/w3varann/tools/Genomon/run.sh
をアップデートしました。
