### ISSUE TITLE
STAR-fusion can't locate Set/IntervalTree.pm

### ISSUE THREAD

**Issue by roko-t** [eigoshimizu/Genomon#39]
/home/w3varann/tools/STAR-Fusion-master/STAR-Fusion --chimeric_out_sam ./results/MCF-7_yshira_100/out/20150707/star/MCF-7_yshira_100/sequence1_Chimeric.out.sam --chimeric_junction ./results/MCF-7_yshira_100/out/20150707/star/MCF-7_yshira_100/sequence1_Chimeric.out.junction --ref_GTF /home/w3varann/database/GTF/refFlat_hg19.gtf --out_prefix ./results/MCF-7_yshira_100/out/20150707/star_fusion/MCF-7_yshira_100/sequence1

Can't locate Set/IntervalTree.pm in @INC (@INC contains: /usr/local/lib/perl5/site_perl/5.14.2/x86_64-linux-thread-multi /usr/local/lib/perl5/site_perl/5.14.2 /usr/local/lib/perl5/5.14.2/x86_64-linux-thread-multi /usr/local/lib/perl5/5.14.2 .) at /home/w3varann/tools/STAR-Fusion-master/STAR-Fusion line 10.
BEGIN failed--compilation aborted at /home/w3varann/tools/STAR-Fusion-master/STAR-Fusion line 10.

**Comment by eigoshimizu** [comment]
run.sh にPERL5LIBを設定しました。

export PERL5LIB=/home/w3varann/.local/lib/perl/lib:/home/w3varann/.local/lib/perl/lib/perl5:/home/w3varann/.local/lib/perl/lib/perl5/x86_64-linux-thred-multi
