### ISSUE TITLE
STAR was completed successfully. But pipeline doesn't start from the next step star-fusion 

### ISSUE THREAD

**Issue by roko-t** [eigoshimizu/Genomon#41]
1. copy run.sh to my work dir  .../hiroko/WORK/FG_performance/w3Genomon 
2. Change analysis_date in _job.yaml
          today -> 20150707

Pipe line has restarted from STAR.

**Comment by eigoshimizu** [comment]
ステータスファイルの名前が間違っていました。
解決です。
ありがとうございました。
