### ISSUE TITLE
Star-fusion : uffus.ruffus_exceptions.RethrownJobError

### ISSUE THREAD

**Issue by roko-t** [eigoshimizu/Genomon#42]
STDERR:

    Completed Task = 'helpers.star_pipeline.star'
    Task enters queue = 'helpers.star_pipeline.star_fusion'
    #star_fusion
    qsub
    command     = .../results/MCF-7_yshira_100/script/star_fusion_20150708_1322_214676.sh
    cmd_options = -l ljob,s_vmem=16G,mem_req=16G

    STDOUT: Your job 409850 ("star_fusion_20150708_1322_214676.sh") has been submitted
Job 409850 exited with exit code 2.

    STDERR:

    star_fusion: runtask failed

    Exception #1
      'exceptions.KeyError('error')' raised in ...
       Task = def helpers.star_pipeline.star_fusion(...):
       Job  = [.../MCF-7_yshira_100/sequence1_Chimeric.out.sam -> .../MCF-7_yshira_100/sequence1_Chimeric.out.junction, .../MCF-7_yshira_100/sequence1]

    Traceback (most recent call last):
      File "/home/w3varann/.local/lib/python2.7/site-packages/ruffus/task.py", line 749, in run_pooled_job_without_exceptions
        register_cleanup, touch_files_only)
      File "/home/w3varann/.local/lib/python2.7/site-packages/ruffus/task.py", line 565, in job_wrapper_io_files
        ret_val = user_defined_work_func(*params)
      File "/sshare4/type-b_proj/var-anno/tools/Genomon/helpers/star_pipeline.py", line 385, in star_fusion
        function = whoami()))
    KeyError: 'error'

    main: Unexpected error
    <class 'ruffus.ruffus_exceptions.RethrownJobError'>: genomon.py:414

**Comment by eigoshimizu** [comment]
star_fusionが失敗していました。
解決です。
ありがとうございました。
