### ISSUE TITLE
Star-fusion : Can't locate Set/IntervalTree.pm

### ISSUE THREAD

**Issue by roko-t** [eigoshimizu/Genomon#43]
Can't locate Set/IntervalTree.pm in @INC (@INC contains: /usr/local/lib/perl5/site_perl/5.14.2/x86_64-linux-thread-multi /usr/local/lib/perl5/site_perl/5.14.2 /usr/local/lib/perl5/5.14.2/x86_64-linux-thread-multi /usr/local/lib/perl5/5.14.2 .) at /home/w3varann/tools/STAR-Fusion-master/STAR-Fusion line 10.

run.sh の export PERL5LIB　のpathがx86_64-linux-thread-multi ではなく　thred-multi 
になっている

**Comment by eigoshimizu** [comment]
STAR-FUSION 実行スクリプトに、 PERL5LIB を設定することで、解決。
ありがとうございました。
