### ISSUE TITLE
bwa memでは-R で@RGを追加する。

### ISSUE THREAD

**Issue by ken0-1n** [eigoshimizu/Genomon#6]
GATKのUnifiedGenotyperを動かそうと思ったらRGがないのでエラーになりました
is malformed: Read (xxxxx省略) is either missing the read group or its read group is not defined in the BAM header, both of which are required by the GATK

RGは入れた方が良いようです。
どのような値を設定すれば良いのかはTCGAなど、世界標準を調べた方が良いかもしれません。

ちなみに、PCAWGのworkflowではbwa memで-Rはつけています

**Comment by ken0-1n** [comment]
GATK 3.3-0 (2015/3/23最新version）でもRGがないBAMはmalformedとされました。

**Comment by eigoshimizu** [comment]
job configuration file に、下記のものを追加します。
#
# SAM file header @RG
#   <examle>
# @RG   ID:110701_SN590_0094_AC02UYABXX SM:TCGA-05-4418-10A-01D-1203-02 LB:Homo_sapiens_assembly19  PL:Illumina_HiSeq2000   CN:Harvard_GCC_02 PI: 200
#
rg_id:              SRR330441           #@RG ID:
sample_desc:        test_sample         #@RG SM:
platform:           Illumina            #@RG PL:
library:            unknown             #@RG LB:
platform_unit:      flowcell-barcode    #@RG PU:
seq_center:         HGC                 #@RG CN:
pred_med_insert:    500                 #@RG PI:

**Comment by eigoshimizu** [comment]
テスト完了。
GitHubにアップしました。
