### ISSUE TITLE
BAM sortに関して

### ISSUE THREAD

**Issue by eigoshimizu** [eigoshimizu/Genomon#9]
1) FASTQ をスプリットする (split)
2) Alignment をする (bwa mem)
3) BAM ファイルを sort をする (samtools sort)
4) BAM ファイルに index をつける (samtools index)
5) BAM ファイルから Region ごとにデータを取り出す (samtools view)
6) Region ごとの BAM ファイルを merge する (samtools cat)
7) Region ごとの BAM ファイルを sort する (samtools sort)
8) samtools cat で merge する (samtools cat)

**Comment by ken0-1n** [comment]
1) FASTQ をスプリットする (split)
2) Alignment をする (bwa mem)
3) BAM ファイルを sort をする (biobambam bamsort, option create index)
4) BAM ファイルから Region ごとにデータを取り出す (samtools view)
5) Region ごとの BAM ファイルを merge する (samtools cat)
6) Mark duplicate (biobambam bammarkduplicates, option create index)
こちらでいかがでしょう

**Comment by eigoshimizu** [comment]
Performance comparison
Method 1 (samtools cat)
1) FASTQ をスプリットする (split)
2) Alignment をする (bwa mem)
3) BAM ファイルを sort をする (samtools sort)
4) BAM ファイルに index をつける (samtools index)
5) BAM ファイルから Region ごとにデータを取り出す (samtools view)
6) Region ごとの BAM ファイルを merge する (samtools merge)
7) samtools cat で merge する (samtools cat)

real	24m43.452s
user	23m55.027s
sys	0m41.941s

**Comment by eigoshimizu** [comment]
Method 2 (samtools merge)

1) FASTQ をスプリットする (split)
2) Alignment をする (bwa mem)
3) BAM ファイルを sort をする (samtools sort)
4) BAM ファイルに index をつける (samtools index)
5) BAM ファイルを merge する (samtools merge)

real	17m18.339s
user	16m52.829s
sys	0m22.769s

**Comment by friend1ws** [comment]
こちらってどのくらいのサイズで実験されてますかね？サイズによってソートとかn log nで変わってきますし、結構違うはずです。
WGSを想定しているので、depthが30〜40のかなり大規模なデータでやった方が良いと思います。
例えば今ATLのデータを解析しまくっているから、そのfastqを使うというのも手ですね。

**Comment by eigoshimizu** [comment]
現在並列化はしないで、シリアルに実行しています。
Region で分けた時に、並列化して、速くなると思います。

**Comment by eigoshimizu** [comment]
Array job 並列

Data
-rw-r--r-- 1 eigos hgc0361   270841455 Mar 30 18:34 SRR330441_1_000000.bam
-rw-r--r-- 1 eigos hgc0361   266888724 Mar 30 18:44 SRR330441_1_000001.bam
-rw-r--r-- 1 eigos hgc0361   266508579 Mar 30 18:44 SRR330441_1_000002.bam
-rw-r--r-- 1 eigos hgc0361   267743217 Mar 30 18:45 SRR330441_1_000003.bam
-rw-r--r-- 1 eigos hgc0361   267074677 Mar 30 18:47 SRR330441_1_000004.bam
-rw-r--r-- 1 eigos hgc0361   266453976 Mar 30 18:55 SRR330441_1_000005.bam
-rw-r--r-- 1 eigos hgc0361   266806048 Mar 30 18:55 SRR330441_1_000006.bam
-rw-r--r-- 1 eigos hgc0361   268070286 Mar 30 18:56 SRR330441_1_000007.bam
-rw-r--r-- 1 eigos hgc0361   268663994 Mar 30 18:58 SRR330441_1_000008.bam
-rw-r--r-- 1 eigos hgc0361   268947074 Mar 30 19:00 SRR330441_1_000009.bam
-rw-r--r-- 1 eigos hgc0361   268124716 Mar 30 19:05 SRR330441_1_000010.bam
-rw-r--r-- 1 eigos hgc0361   267244260 Mar 30 19:06 SRR330441_1_000011.bam
-rw-r--r-- 1 eigos hgc0361   267113992 Mar 30 19:07 SRR330441_1_000012.bam
-rw-r--r-- 1 eigos hgc0361   267516303 Mar 30 19:08 SRR330441_1_000013.bam
-rw-r--r-- 1 eigos hgc0361   266846015 Mar 30 19:10 SRR330441_1_000014.bam
-rw-r--r-- 1 eigos hgc0361   267836496 Mar 30 19:17 SRR330441_1_000015.bam
-rw-r--r-- 1 eigos hgc0361   267367302 Mar 30 19:19 SRR330441_1_000016.bam
-rw-r--r-- 1 eigos hgc0361   266640678 Mar 30 19:20 SRR330441_1_000017.bam
-rw-r--r-- 1 eigos hgc0361   267570655 Mar 30 19:20 SRR330441_1_000018.bam
-rw-r--r-- 1 eigos hgc0361   267347737 Mar 30 19:25 SRR330441_1_000019.bam
-rw-r--r-- 1 eigos hgc0361   266285549 Mar 30 19:32 SRR330441_1_000020.bam
-rw-r--r-- 1 eigos hgc0361   267181671 Mar 30 19:32 SRR330441_1_000021.bam
-rw-r--r-- 1 eigos hgc0361   161908624 Mar 30 19:47 SRR330441_1_000022.bam
Old method (samtools merge)
/home/eigos/BamSort/old.sh

Wed Apr  1 13:40:29 JST 2015 (samtools sort, samtools index)
qsub -sync y -t 1-23:1 -l s_vmem=8G,mem_req=8 -l ljob -o /home/eigos/Log -e /home/eigos/Log /home/eigos/Tmp/sort_201504011340894561276.sh

Wed Apr  1 13:44:29 JST 2015 (samtools merge)
qsub -sync y -l s_vmem=8G,mem_req=8 -l ljob -o /home/eigos/Log -e /home/eigos/Log /home/eigos/Tmp/merge_201504011344019550216.sh

Wed Apr  1 14:16:29 JST 2015

real    36m0.227s
user    0m0.212s
sys    0m0.277s

**Comment by eigoshimizu** [comment]
New method (samtools cat)
/home/eigos/BamSort/new.sh

Wed Apr  1 14:27:36 JST 2015 (samtools sort)
qsub -sync y -t 1-23:1 -l s_vmem=8G,mem_req=8 -l ljob -o /home/eigos/Log -e /home/eigos/Log /home/eigos/Tmp/sort_201504011427042930726.sh

Wed Apr  1 14:31:36 JST 2015 (samtools view by region)
qsub -sync y -t 1-42:1 -l s_vmem=8G,mem_req=8 -l ljob -o /home/eigos/Log -e /home/eigos/Log /home/eigos/Tmp/view_201504011431082922186.sh
qsub -sync y -t 1-42:1 -l s_vmem=8G,mem_req=8 -l ljob -o /home/eigos/Log -e /home/eigos/Log /home/eigos/Tmp/view_201504011431114810586.sh
qsub -sync y -t 1-42:1 -l s_vmem=8G,mem_req=8 -l ljob -o /home/eigos/Log -e /home/eigos/Log /home/eigos/Tmp/view_201504011431136735982.sh
qsub -sync y -t 1-42:1 -l s_vmem=8G,mem_req=8 -l ljob -o /home/eigos/Log -e /home/eigos/Log /home/eigos/Tmp/view_201504011431159567437.sh
qsub -sync y -t 1-42:1 -l s_vmem=8G,mem_req=8 -l ljob -o /home/eigos/Log -e /home/eigos/Log /home/eigos/Tmp/view_201504011431181643484.sh
qsub -sync y -t 1-42:1 -l s_vmem=8G,mem_req=8 -l ljob -o /home/eigos/Log -e /home/eigos/Log /home/eigos/Tmp/view_201504011431229288603.sh
qsub -sync y -t 1-42:1 -l s_vmem=8G,mem_req=8 -l ljob -o /home/eigos/Log -e /home/eigos/Log /home/eigos/Tmp/view_201504011431253400693.sh
qsub -sync y -t 1-42:1 -l s_vmem=8G,mem_req=8 -l ljob -o /home/eigos/Log -e /home/eigos/Log /home/eigos/Tmp/view_201504011431276591565.sh
qsub -sync y -t 1-42:1 -l s_vmem=8G,mem_req=8 -l ljob -o /home/eigos/Log -e /home/eigos/Log /home/eigos/Tmp/view_201504011431299195358.sh
qsub -sync y -t 1-42:1 -l s_vmem=8G,mem_req=8 -l ljob -o /home/eigos/Log -e /home/eigos/Log /home/eigos/Tmp/view_201504011431322559038.sh
qsub -sync y -t 1-42:1 -l s_vmem=8G,mem_req=8 -l ljob -o /home/eigos/Log -e /home/eigos/Log /home/eigos/Tmp/view_201504011431345962792.sh
qsub -sync y -t 1-42:1 -l s_vmem=8G,mem_req=8 -l ljob -o /home/eigos/Log -e /home/eigos/Log /home/eigos/Tmp/view_201504011431370016288.sh
qsub -sync y -t 1-42:1 -l s_vmem=8G,mem_req=8 -l ljob -o /home/eigos/Log -e /home/eigos/Log /home/eigos/Tmp/view_201504011431394067759.sh
qsub -sync y -t 1-42:1 -l s_vmem=8G,mem_req=8 -l ljob -o /home/eigos/Log -e /home/eigos/Log /home/eigos/Tmp/view_201504011431417214883.sh
qsub -sync y -t 1-42:1 -l s_vmem=8G,mem_req=8 -l ljob -o /home/eigos/Log -e /home/eigos/Log /home/eigos/Tmp/view_201504011431440774019.sh
qsub -sync y -t 1-42:1 -l s_vmem=8G,mem_req=8 -l ljob -o /home/eigos/Log -e /home/eigos/Log /home/eigos/Tmp/view_201504011431464909004.sh
qsub -sync y -t 1-42:1 -l s_vmem=8G,mem_req=8 -l ljob -o /home/eigos/Log -e /home/eigos/Log /home/eigos/Tmp/view_201504011431542989470.sh
qsub -sync y -t 1-42:1 -l s_vmem=8G,mem_req=8 -l ljob -o /home/eigos/Log -e /home/eigos/Log /home/eigos/Tmp/view_201504011431566358800.sh
qsub -sync y -t 1-42:1 -l s_vmem=8G,mem_req=8 -l ljob -o /home/eigos/Log -e /home/eigos/Log /home/eigos/Tmp/view_201504011431588893671.sh
qsub -sync y -t 1-42:1 -l s_vmem=8G,mem_req=8 -l ljob -o /home/eigos/Log -e /home/eigos/Log /home/eigos/Tmp/view_201504011431612214829.sh
qsub -sync y -t 1-42:1 -l s_vmem=8G,mem_req=8 -l ljob -o /home/eigos/Log -e /home/eigos/Log /home/eigos/Tmp/view_201504011431635103458.sh
qsub -sync y -t 1-42:1 -l s_vmem=8G,mem_req=8 -l ljob -o /home/eigos/Log -e /home/eigos/Log /home/eigos/Tmp/view_201504011431658576991.sh
qsub -sync y -t 1-42:1 -l s_vmem=8G,mem_req=8 -l ljob -o /home/eigos/Log -e /home/eigos/Log /home/eigos/Tmp/view_201504011431681985903.sh

Wed Apr  1 14:45:36 JST 2015 (samtools merge of each region)
qsub -sync y -t 1-42:1 -l s_vmem=8G,mem_req=8 -l ljob -o /home/eigos/Log -e /home/eigos/Log /home/eigos/Tmp/merge_201504011445719377933.sh

Wed Apr  1 14:53:36 JST 2015 (samtools cat)
qsub -sync y -l s_vmem=8G,mem_req=8 -l sjob -o /home/eigos/Log -e /home/eigos/Log /home/eigos/Tmp/cat_201504011453936815122.sh

Wed Apr  1 14:55:36 JST 2015

real    28m0.949s
user    0m1.985s
sys    0m1.525s

**Comment by eigoshimizu** [comment]
bammarkduplicates は、bamsort でソートされた結果のフラグが必要。
samtools view の結果のファイルを入力すると失敗する。
[eigos@ngw01 data.md :( ]$ bammarkduplicates I=SRR330441_1_sorted_chr1:0-99999999.bam I=SRR330441_1_sorted_chr1:100000000-199999999.bam O=tmp.bam
[V] output compression level -1
BamMergeTemplate::BamMergeTemplate(): cannot merge, not all files are marked as sorted.

必要なフラグ。
@PG	ID:bamsort	PN:bamsort	CL:bamsort index=1 indexfilename=./data.md/SRR330441_1_000000_sorted.bam.bai I=./data.md/SRR330441_1_000000_unsorted.bam O=./data.md/SRR330441_1_000000_sorted.bam	PP:bwa	VN:0.0.188

**Comment by eigoshimizu** [comment]
処理方法
1) Biobambam による sort と markduplicates
    bamsort でソートし、 bammarkduplicates で merge と markduplicates を実行。

2) Samtools による sort と Picard による markduplicates
    samtools sort でソートし、 samtools index でインデックスを作り、
    samtools merge でマージし、samtools index でインデックスを作り、
    picard MarkDuplicates で markduplicates を実行。


かかった時間の比較
biobambam:    6分１秒
samtools+picard:    8分0秒

使用メモリ
bamsort:    2.0G
bammarkduplicates:    0.6G

samtools sort:    0.2G
picard markduplicates: 7.1G (java -Xmx6G -Xms2G -jar MarkDuplicates)

samtools view で sam file に変換した結果の比較
Header の違い：
ファイルを添付してあります。
<@PG の違い>
@PG ID:bammarkduplicates
@PG ID:bamsort                      x マージしたファイルの数だけあります。
@PG ID:bwa                            x マージしたファイルの数だけあります。
----------
@PG ID:MarkDuplicates
@PG ID:bwa                            x 1

Read での違い：
read 自体は全て一致しました。 optional fields に、下記にように少し違いがありますが、問題はないと思われます。

Picard MarkDuplicates
MD:Z:50 PG:Z:MarkDuplicates RG:Z:SRR330441  NM:i:0  AS:i:50 XS:i:50

Biobambam bammarkduplicates
NM:i:0  MD:Z:50 AS:i:50 XS:i:50 RG:Z:SRR330441         



使用したデータ：　30M bam file x 10
-rw-r--r-- 1 eigos icgc_pan 30652445 Apr  8 17:19 SRR330441_1_000000_unsorted.bam
-rw-r--r-- 1 eigos icgc_pan 30775027 Apr  8 17:19 SRR330441_1_000001_unsorted.bam
-rw-r--r-- 1 eigos icgc_pan 30578255 Apr  8 17:19 SRR330441_1_000002_unsorted.bam
-rw-r--r-- 1 eigos icgc_pan 30852310 Apr  8 17:20 SRR330441_1_000003_unsorted.bam
-rw-r--r-- 1 eigos icgc_pan 30591805 Apr  8 17:20 SRR330441_1_000004_unsorted.bam
-rw-r--r-- 1 eigos icgc_pan 30902142 Apr  8 17:20 SRR330441_1_000005_unsorted.bam
-rw-r--r-- 1 eigos icgc_pan 30539784 Apr  8 17:20 SRR330441_1_000006_unsorted.bam
-rw-r--r-- 1 eigos icgc_pan 30888128 Apr  8 17:20 SRR330441_1_000007_unsorted.bam
-rw-r--r-- 1 eigos icgc_pan 30574671 Apr  8 17:20 SRR330441_1_000008_unsorted.bam
-rw-r--r-- 1 eigos icgc_pan 30932683 Apr  8 17:19 SRR330441_1_000009_unsorted.bam

**Comment by eigoshimizu** [comment]
bam sort および markduplicate は、
biobambam と samtools sort, index, picard markduplicates に対応しました。

use_biobambam: True
を job configuration file に指定することで、biobambam を使用します。
デフォルトは、 False で、samtools および picard を使用します。
